# Generated by Django 2.2 on 2020-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(null=True),
        ),
    ]
