# Generated by Django 2.2 on 2020-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('codigo', models.AutoField(default=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('codigo', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('localizacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AddField(
            model_name='libro',
            name='codigo',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
