# Generated by Django 2.2 on 2020-05-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_auto_20200515_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='codigo_lbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
    ]
