# Generated by Django 2.2 on 2020-05-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_auto_20200515_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='codigo_lbr',
        ),
        migrations.AddField(
            model_name='libro',
            name='codigo_lbr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='codigo',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo_usr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Usuario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigo_eje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Ejemplar'),
        ),
    ]
