# Generated by Django 2.2 on 2020-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_auto_20200515_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='codigo_usr',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_ejem',
            field=models.ManyToManyField(to='libros.Ejemplar'),
        ),
    ]
