# Generated by Django 2.2 on 2020-06-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0012_auto_20200618_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='codigo_lbr',
            new_name='codigo_aut',
        ),
    ]
