# Generated by Django 2.2 on 2020-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0013_auto_20200618_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cod_usr',
            field=models.IntegerField(null=True),
        ),
    ]
